### ISSUE TITLE
Memory innodb buffer pool size calculation for MySQL 5.7

### ISSUE THREAD

**Issue by jmrenouard** [major/MySQLTuner-perl#155]
innodb buffer pool size is no more the reference in 5.7:

https://bugs.mysql.com/bug.php?id=80350

http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_buffer_pool_chunk_size

We need a patch for calculations for this version(5.7.X)

**Comment by morgo** [comment]
AFAIK, this is an edge case caused by an alignment factor known as `innodb_buffer_pool_chunk_size`.  It does not usually make sense to have 64 instances with a 9G buffer pool.

An alternative could be to warn when the buffer pool instance count is greater than 8 **and** greater than 1G per buffer pool.

(The alignment factor can also not be distinguished as different from someone changing the size of `innodb-buffer-pool-size` while the server is running.)

**Comment by jmrenouard** [comment]
in MySQL 5.7, There is some subtilities.
InnoDB Buffer Pool Size is not equals to innodb_buffer_pool_size value.

InnoDB Buffer Pool size is equals or greater to innodb_buffer_pool_size 

So to be sure it will works perfectly.
innodb_buffer_pool_size should be a multiple of innodb_buffer_pool_chunk_size*innodb_buffer_pool_instances.

Related documentation:
https://dev.mysql.com/doc/refman/5.7/en/innodb-buffer-pool-resize.html
Buffer pool size must always be equal to or a multiple of innodb_buffer_pool_chunk_size * innodb_buffer_pool_instances

**Comment by jmrenouard** [comment]
Hi @morgo 

What do you think about last version including test regarding values for innodb_buffer_pool_size,innodb_buffer_pool_chunk_size and innodb_buffer_pool_instances ?

Thanks for your feedback.
@jmrenouard

**Comment by morgo** [comment]
Looks good to me. Thanks!

**Comment by jmrenouard** [comment]
Thanks for your feedback @morgo 

I close this issue. Feel free to reopen it if needed.
@jmrenouard
