### ISSUE TITLE
Question about fragmented tables

### ISSUE THREAD

**Issue by smutel** [major/MySQLTuner-perl#207]
Hello,

I don't understand why I have this message using mysqltuner:
[!!] Total fragmented tables: 33

I launched optimize on each table and I run mysqltuner again.
I have the same message.

Could you help me on this topic ?
Thanks.

**Comment by jmrenouard** [comment]
Hi @smutel 

I think this question is discussed there:
http://serverfault.com/questions/202000/how-find-and-fix-fragmented-mysql-tables

You will have a complete point of view regarding fragmentation.

Tell us if it 's clear after reading all the answers.
@jmrenouard

**Comment by jkavalik** [comment]
Hi @smutel,

are your tables InnoDB? IMHO table fragmentation like this has only meaning for MyISAM tables (heap). InnoDB stores data in B-Tree, with 16KB blocks by default, and it always keeps some free space in there (so the check on `data_free` does not tell much) and these blocks are dynamically split/merged during operations as the tree balances itself.

@jmrenouard, I would like to suggest to only check MyISAM tables for fragmentation. InnoDB fragmentation is not as easy to detect and `OPTIMIZE TABLE` is not effective for the *"fragmentation"* detected by there being free space in the table (and is not needed for InnoDB otherwise).

InnoDB fragmentation exists, but is a much more complex issue which is not very often encountered in practice - https://www.percona.com/blog/2009/11/05/innodb-look-after-fragmentation/

**Comment by jmrenouard** [comment]
I close this issue regarding @smutel last PR merged.
