### ISSUE TITLE
problems with mariadb 10.1.12

### ISSUE THREAD

**Issue by angelus2014** [major/MySQLTuner-perl#228]
I'm running MySQL version 10.1.12-MariaDB which the scripts reports as being supported: "[OK] Currently running supported MySQL version 10.1.12-MariaDB", but after running the script the MariaDB instance is left in a rather 'broken' state. If I just run a simple statement like "show tables;", I get the following error: "ERROR 1018 (HY000): Can't read dir of '.' (errno: 24 "No file descriptors available")". If I restart MariaDB and issue the same statement again, it just works with no error.

The OS is a LXC container running Alpine Linux

Regards,

Angelo

**Comment by jmrenouard** [comment]
Hi @angelus2014,

I think this issue is related to installation or MariaDB on Alpine Linux.
As long as MariaDB responds ERROR 1018, MySQLTuner will fail as well.

MySQLTuner is supposed to work with an operational MySQL/Major server.
MySQLTuner is not running any insert, update or drop on MySQL server.

Maybe you get to lower value for your system limits:
http://i-learnings.blogspot.fr/2012/11/error-1018-hy000-cant-read-dir-of-errno.html

Best regards,
@jmrenouard

**Comment by jmrenouard** [comment]
I close this issue due to it is a problem from your system settings.

Feel free to reopen it if needed.
@jmrenouard

**Comment by angelus1969** [comment]
I don't think it's related to MariaDB on Alpine, because as I said, prior to running the mysqltuner script, the service is running well. Only after running the script, the MariaDB instance has problems.
Besides that, I didn't notice this behavior with the previous version of the script.

Regards,

Angelo

**Comment by jkavalik** [comment]
@angelus1969 hello,

the error message states 

> (errno: 24 "No file descriptors available")

which could come from the tuner doing a scan on all tables (to check fragmentation, data size and such statistics) and your server not being able to cope with that many tables being opened. The same might happen without the tuner script if some user read from too many tables (a backup jobs for example do that). Fix your OS open files limit.
