### ISSUE TITLE
User 'munin@localhost' has user name as password.

### ISSUE THREAD

**Issue by slrslr** [major/MySQLTuner-perl#233]
Hello,

please where is described what means this MySQLTuner warning? So i can fix it

User 'munin@localhost' has user name as password.
User 'xyxyxyxy@%' hasn't specific host restriction.

Thank you

**Comment by jmrenouard** [comment]
Hi @slrslr 

munin user get 'munin' as password and it is a too simple password to find.

Xyzxyzxyz user can be used from any other machines in the network.
prefer using 'xyxyxyxy@192.168.% user so that only machine from 192.168.0.0 network can connect to your mysql server.

Best reagards,
@jmrenouard
