### ISSUE TITLE
MySQL memory usage exceeding "Maximum Possible Memory Usage"

### ISSUE THREAD

**Issue by peppies** [major/MySQLTuner-perl#378]
Greetings,

In mysqltuner, I have a maximum possible memory usage of:
    [OK] Maximum reached memory usage: 459.1M (46.27% of installed RAM)
    [OK] Maximum possible memory usage: 699.8M (70.52% of installed RAM)

When I use the "top" command, MySQL is using 745MB of RAM and eventually crashes. Why isn't MySQL following the maximum possible memory usage displayed by mysqltuner? It seems this is not correct.

  PID USER      PR  NI    VIRT        RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 1132 mysql    20   0 2223084  745344   0   S      1.7     73.4     424:28.27    mysqld

**Comment by jmrenouard** [comment]
hi @peppies 

There is a differnce beetween Virtual memory and real memory 
# free 
              total        used        free      shared  buff/cache   available
Mem:        1883996      537448      122456         496     1224092     1297272
Swap:       1048572         576     1047996

free -t
              total        used        free      shared  buff/cache   available
Mem:        1883996      537308      122596         496     1224092     1297420
Swap:       1048572         576     1047996
Total:      2932568      537884     1170592

Counting virtual memory usage shows hight value than real free memory.
https://www.logicmonitor.com/blog/the-right-way-to-monitor-virtual-memory-on-linux/

Hope it will anwser your question.

**Comment by trexx** [comment]
Hi @jmrenouard would you be able to further elaborate on your answer?

In the top snipped pasted by the OP, its showing an RSS of 745344 (745MB), it seems like the server has roughly just over 1GB of RAM. Yet maximum possible memory usage reported by mysqltuner is significantly lower. I am also seeing the same results.
If I may take a stab at this, I believe mysqltuners numbers come purely from mysql configuration. Whereas the likes of top, ps, etc would also include the overhead from executing the binary, shared libraries and resources, etc.

**Comment by jbowen7** [comment]
MySQLTuner-perl: 1.7.13  commit # c8fb973bf85c87f802ad73f4ca86802b1c32c669
Server version: 5.6.26-74.0-log Percona Server (GPL), Release 74.0, Revision 32f8dfd

@jmrenourard, this appears to be a bug

I'm seeing the same as reported by @peppies. However, in my case, the discrepancy is off by such a large amount  that it can't be due to just binaries and shared libraries. The attached memory mapping below shows as much.

Maximum reached memory indicates 113.9G. The actual usage is closer to 121G (RSS, indicated by pmap)

There are definitely some variables that are not included in 
```
$mycalc{'per_thread_buffers'}
$mycalc{'server_buffers'}
```
Examples:
net_buffer_length
max_digest_length
table_open_cache
table_definition_cache

Though.. I don't suspect their exclusion is the result of my discrepancy.
I'll dig around and let you know what I find.

```
[--] Physical Memory     : 125.9G
[--] Max MySQL memory    : 115.3G
[--] Other process memory: 38.1M
[--] Total buffers: 96.1G global + 1.1M per thread (2000 max threads)
[--] P_S Max memory usage: 17G
[--] Galera GCache Max memory usage: 0B
[!!] Maximum reached memory usage: 113.9G (90.41% of installed RAM)
[!!] Maximum possible memory usage: 115.3G (91.54% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
```
```
[root@ia7sb MySQLTuner-perl]$ free -m
             total       used       free     shared    buffers     cached
Mem:        128953     128565        388          0        155       2658
-/+ buffers/cache:     125751       3202 
Swap:        18001       1925      16075 
```
```
[root@ia7sb MySQLTuner-perl]$ ps aux --sort -rss
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mysql    20869  336 96.3 144530384 127269140 ? Sl   Oct08 3957:46 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql/ --plugin-dir=/usr/lib64/mysql
```

See memory full memory mapping. 

[mmap.txt](https://github.com/major/MySQLTuner-perl/files/2462604/mmap.txt)

**Comment by jbowen7** [comment]
connection buffer and result buffer are not in the calculation of $mycalc{'max_total_per_thread_buffers'}

* although this would be very hard  to calculate since for each packet the value is in a range.
net_buffer_length <= connection buffer <= max_allowed_packet
net_buffer_length <= result buffer <= max_allowed_packet

This will cause a discrepancy; results will be varied.

@peppies ,What version of MySQL and mysqltuner.pl are you using?
Can you check these variables: 
```
SHOW VARIABLES LIKE 'net_buffer_length';
SHOW VARIABLES LIKE 'max_allowed_packet'';
```
and the status of
```
SHOW STATUS LIKE 'Max_used_connections'
```

**Comment by jmrenouard** [comment]
Same as Percona wrong memory calculation #456
