### ISSUE TITLE
Mysqltuner is stuck on selecting from information_schema.TABLES

### ISSUE THREAD

**Issue by mtxd** [major/MySQLTuner-perl#391]
The select never finishes:

|  47561 | root        | localhost          | NULL      | Query   | 12580 | Opening tables     | SELECT CONCAT(CONCAT(TABLE_SCHEMA, '.'), TABLE_NAME),DATA_FREE FROM information_schema.TABLES WHERE  |    0.000 |

Mysqltuner 1.7.9
Mariadb 10.1.30 + galera clustering.

**Comment by jmrenouard** [comment]
Hi @mtxd 
Strange !

Do you face other technical issue at the same time ?
Freezing Galera Cluster, disk in Read only mode orDisk space issue ?


This SQL request is simply get all the table and schema on your server.
you can try innodb_stats_on_metadata=0, but without any guaranted.

Is it a issue in MariaDB 10.1.30
Thanks for you feedback.

**Comment by jmrenouard** [comment]
Is there any feedback on this issue ?
Is there anybody facing this issue ?

**Comment by jmrenouard** [comment]
We face same issue when there is a lot of databases and tables.
Best regards,

**Comment by mtxd** [comment]
No other issues, DB is functioning as it is expected to.

**Comment by jmrenouard** [comment]
Hi,

I recently faced same issue. Can you tell me how many databases you are currently hosting on your Galera Cluster ?

This appears when requesting information_schema during a load and optimizer try to access at the same time same datas.

**Comment by jmrenouard** [comment]
You can try this solution:
https://www.percona.com/blog/2011/12/23/solving-information_schema-slowness/

innodb_stats_on_metadata=0

Best regards,

**Comment by mtxd** [comment]
~600. I will try "innodb_stats_on_metadata=0".

**Comment by jmrenouard** [comment]
Hi @mtxd 

There is a new option you can try: --notbstat.

This is one of the reason for slowness in mysqltuner.

You can grab last 1.7.12 version at least to test this new option.

Best regards,

**Comment by jmrenouard** [comment]
Hi @mtxd @babinomec 
I used a MT which take a long long time compiling a full report

I think this is not an issue as long as you get some time and coffee :) 

It can be logical that calculation take a long time based on 100654 tables inside your database server

In this case, I suggest splitting your datas into several database servers according to data usage
For example, analytics datas(big calculation every night) should be separated from main databases (Web server or application datas for clients or enterprise apps datas)

I also suggest not duplicate datas for practical operational reasons and try to fix this issue if possible with dev teams 
Eliminate datas is a good way to improve data performance and is also an ecofriendly approach

I closed this issue because I don't want to limit number of analysed tables for computation time reason
