### ISSUE TITLE
Needs update to take account for performance_schema memory usage.

### ISSUE THREAD

**Issue by kmcfate** [major/MySQLTuner-perl#40]
Please see http://bugs.mysql.com/bug.php?id=68514

Additional memory is pre-allocated per allowed connection. This makes max_connections much more important when calculating memory usage. The script should account for this when doing memory calculations on >=5.6

**Comment by jmrenouard** [comment]
Somebody know how to calculate PFS overall used memory and max used memory ?

**Comment by jmrenouard** [comment]
Issue #96 is a precision around memory usage.

**Comment by jmrenouard** [comment]
I will propose to included 1 GO RAM  by default as size for performance schema memory consummation.

Is it ok for everybody ?

**Comment by morgo** [comment]
I have some advice on how `P_S` allocates memory:

- In MySQL 5.6 it is fixed in size, and allocated all in advance on server startup.  You can see the total size from `show engine performance_schema status` - particular value is `performance_schema.memory`.

- In MySQL 5.7+, the memory consumption allocates in chunks.  It is still visible in  `show engine performance_schema status`, but you need to allow for some ramp up time.  The details are described [in this blog post](http://mysqlserverteam.com/new-in-mysql-5-7-performance-schema-scalable-memory-allocation/).

**Comment by jmrenouard** [comment]
Thnaks @morgo

**Comment by jmrenouard** [comment]
Last commit add performance_schema.memory in memory calculation formulas.
