### ISSUE TITLE
Incorrect memory stats for version 1.7.19

### ISSUE THREAD

**Issue by bradp-wordkeeper** [major/MySQLTuner-perl#472]
I just noticed an issue in the memory calculations for this version.  In version 1.7.19 it shows this on the server I was just working on.

[!!] Maximum reached memory usage: 5.7G (317.30% of installed RAM)
[!!] Maximum possible memory usage: 50.9G (2835.64% of installed RAM)

This server only has 2G of ram and 512M of swap so it's actually impossible for it to have reached that level to begin with.

Then I checked the output for version 1.7.17 and got accurate results.

[OK] Maximum reached memory usage: 712.3M (38.75% of installed RAM)
[OK] Maximum possible memory usage: 922.0M (50.16% of installed RAM)

**Comment by bradp-wordkeeper** [comment]
Oh this was running against MariaDB 10.4.11 if that makes any difference

**Comment by Neurozone** [comment]
Same bug here with MySQL 5.5.62

values are:
join_buffer_size                       = 512K
net_buffer_length                      = 8K
read_buffer_size                       = 256K
read_rnd_buffer_size                   = 512K
sort_buffer_size                       = 128K
thread_cache_size                      = 16
thread_concurrency                     = 32
thread_cache_size                      = 200
thread_stack                           = 256K

key_buffer_size                        = 8M
myisam_sort_buffer_size                = 8M

innodb_buffer_pool_size                = 8G
innodb_log_buffer_size                 = 256M

max_connections                        = 500

And I'm getting:
Total buffers: 8.8G global + 1000.6M per thread (500 max threads)

**Comment by Dcl2049** [comment]
Check your max_allowed_packet values. This accounted for a difference when I noticed this behavior in the most recent version. The new version appears to be calculating this by including this value in per-thread buffers on line 2396, compared to the old version where this is not factored in to the calculation.

**Comment by bradp-wordkeeper** [comment]
That does appear to be the change that makes it show that value.  If I comment that line in version 1.7.19 then it shows the same results as the previous version.  We have the max_allowed_packet set to 1G on that server.

I'm definitely not an expert on this topic so forgive me if this is a dumb question.  Does Mysql/Mariadb actually allocate that amount of ram if it has to send a packet that is that size?

So for example, if it has to send a packet that is 1G exactly would it actually allocate that amount of ram to that thread while it's sending it?  I was under the impression that it was only a network limit.

Thanks!

**Comment by Dcl2049** [comment]
From what I see in the mysql docs:

https://dev.mysql.com/doc/refman/5.7/en/packet-too-large.html

"It is safe to increase the value of this variable because the extra memory is allocated only when needed. For example, mysqld allocates more memory only when you issue a long query or when mysqld must return a large result row. The small default value of the variable is a precaution to catch incorrect packets between the client and server and also to ensure that you do not run out of memory by using large packets accidentally."

So it sounds to me like the value calculated by the latest version script would be a "worst-case scenario" where every single connection is maxing out its memory allocation due to an extremely large result set or query, rather than a real-world value that was likely reached during MySQL runtime.

**Comment by bradp-wordkeeper** [comment]
Thanks Dcl2049!  That makes perfect sense to me.  :)
