### ISSUE TITLE
ASK results from report

### ISSUE THREAD

**Issue by febridev** [major/MySQLTuner-perl#510]
hi currently I got this results after running mysqltuner.pl

```
[!!] Maximum reached memory usage: 59.4G (94.63% of installed RAM)
[!!] Maximum possible memory usage: 776.4G (1237.14% of installed RAM)
[!!] Overall possible memory usage with other process exceeded memory

```
that is recommendation  configuration from mysqltuner to the my mariadb instance ? or that is results from current configuration or current used on my mariadb instance ?

thanks

**Comment by Raphael67** [comment]
Hi, as far as I know :
* The first line is the peak of memory you have really consummed since the start of the server.
* The second line is what you could theorically need if all the connections are used at the same time.
* The third is just to tell you that according to the other processes on your system, if all the connections are used on your server you will need more ram than what you physically have.

Hope it helps.

**Comment by febridev** [comment]
> Hi, as far as I know :
> 
> * The first line is the peak of memory you have really consummed since the start of the server.
> * The second line is what you could theorically need if all the connections are used at the same time.
> * The third is just to tell you that according to the other processes on your system, if all the connections are used on your server you will need more ram than what you physically have.
> 
> Hope it helps.

hi thanks for update,
currently my server have 62GB ram 
so its mean i can setup like `innodb_buffer_pool_size` to 52GB  ?

**Comment by Raphael67** [comment]
`innodb_buffer_pool_size` is the main buffer to handle innodb data. If you use innodb, this should be the biggest you can. It should be at least the size of your whole data + indexes. MySQLTuner should tell you.
