### ISSUE TITLE
Tuner gives false info

### ISSUE THREAD

**Issue by locksmithunit** [major/MySQLTuner-perl#523]
Is a long time i get false info from the tuner.
this from one of the updates of Cpanel, i see people experience that from 2015 until today.
have a way to refresh the script?

I actually try to install that from the beginning:
https://forums.cpanel.net/threads/mysqltuner-shows-wrong-amount-of-installed-ram.491271/

please help.

**Comment by gggeek** [comment]
Hello. I think that you would have had more success with your question if you had mentioned the exact 'false info' in the issue title or description, instead of only putting a link to a 3rd party forum.

As for the problem with the memory reported: if you know how much memory is installed, you can pass it as parameter to the command line, and get the correct responses.

I don't know why it's hard for a perl program to detect on its own the max memory available, but I suspect that it might be related to the fact that the user account used to run the script is not root (which is good), and enhanced linux security configurations might restrict access to that information, such as eg. inability to read /proc/meminfo. In which case, there is very little that can be done to overcome the problem. I would be happy to be proven wrong of course :-)

As for myself, I have always taken the recommendations which are based on the max memory of the server as not very reliable, and this problem does not bother me too much.
The fact is that, even if the max memory available is right, there are way too many usage scenarios which make memory calculations hard or useless: is the server dedicated to mysql ? are other apps running on it? is it a vm, or in a container?
In the end, it's up to you to know the planned server usage and adjust the calculations accordingly...

**Comment by jmrenouard** [comment]
Hi @locksmithunit,

1°  MT is a free software, feel free to contribute anwsering and debugging it 
2° 1.5 version is a old version please try a 1.7.25+ version
https://forums.cpanel.net/threads/mysqltuner-shows-wrong-amount-of-installed-ram.491271/ 

So, I will close this issue because we don't know how to help you :|

Best Regards,
@jmrenouard
