### ISSUE TITLE
The same varibale two times?

### ISSUE THREAD

**Issue by WAdama** [major/MySQLTuner-perl#604]
When I use your script I get for "key_buffer _size" two recommendations:
`Variables to adjust:
    key_buffer_size (~ 14K)
    key_buffer_size (> 117.0K)
`
Is that correct?
Version: 2.0.5
MariaDB 10.3

By the way: During start the script says 2.0.4 even it is 2.0.5

**Comment by pattyland** [comment]
Still in 2.1.1:

```
Variables to adjust:
    key_buffer_size (~ 8K)
    key_buffer_size (> 124.0K)
```
8k and "more than 124k" are also very different values, I don't know what I should use

**Comment by hcooper** [comment]
+1 

MySQLTuner 2.1.7
mysql  Ver 14.14 Distrib 5.7.42

```
Variables to adjust:
    key_buffer_size (~ 1M)
    key_buffer_size (> 32.3M)
```

**Comment by jmrenouard** [comment]
Hi, we are suggesting migrating MyIsam to InnoDB because MyISAM is not longer in use in MySQL and MariaDB start removing MyISAM tables for last version

We develop a --dumpdir option dumping a SQL script migrate_myisam_to_innodb.sql
This script allows us to migrate MYISAM to InnoDB
this should be apply only after migrating to MySQL 5.7/8.0 or MariaDB 10.6  at least
