### ISSUE TITLE
ERROR 1054

### ISSUE THREAD

**Issue by ashcoft** [major/MySQLTuner-perl#615]
ERROR 1054 (42S22) at line 78 in file: './views/p_s/metrics_56.sql': Unknown column 'STATUS' in 'field list'

above error happened after execute mysql -u root -p < ./sys_10.sql

the solution excluding /views/p_s/metrics_56.sql'

system:

Database server

    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server connection: SSL is not being used Documentation
    Server version: 10.9.3-MariaDB - MariaDB Server
    Protocol version: 10
    User: root@localhost
    Server charset: cp1252 West European (latin1)

Web server

    Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9
    Database client version: libmysql - mysqlnd 8.1.11
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation
    PHP version: 8.1.11

phpMyAdmin

    Version information: 5.2.0-1.el7.remi

**Comment by longradix** [comment]
Incorrect repository? Possibly https://github.com/mysql/mysql-sys is meant.

**Comment by jmrenouard** [comment]
Hi,

I will close this issue
You don't need to install sys schema because this is installed by default

README have been changed to indicate that this additional step in not longer needed for MariaDB 10.6 +

I have change README title to enphase this point:
 
Optional Performance schema and Sysschema installation for MariaDB < 10.6
--

Sysschema is not installed by default under MariaDB prior to 10.6 [MariaDB sys](https://mariadb.com/kb/en/sys-schema/)
