### ISSUE TITLE
join buffer size recommendation bug

### ISSUE THREAD

**Issue by zoddshop** [major/MySQLTuner-perl#687]
Tuner is telling me to infinitely increase join buffer size. It keeps asking me to up it and I am now at 300 MB, which is ridiculous and still telling me to up it

    join_buffer_size (> 300.0M, or always use indexes with JOINs)

The DB total size is only 5 Gigs.

**Comment by jmrenouard** [comment]
Hi @zoddshop 
Thanks for separating this issue ;)

**Comment by jmrenouard** [comment]
Hi @zoddshop 

When schema is under-indexed, MT will suggest to increase join_buffer so that you will have enough memory to perform join operation into the memory(RAM) 
There is an other suggestion also present here: "or always use indexes with JOINs", which seem to be the right way to fix this situation

MT is a tool that try to help us to find issue in our MySQL/MariaDB usage model and you should also consider that indexes are a  very effective way to increase data access performance   

I will close this issue because I cannot help improving this specific situation

If I get enough professional staff , maybe I will develop advisor about indexes but it seems to be an hard staff and dedication :)
