### ISSUE TITLE
Patch and test from windows

### ISSUE THREAD

**Issue by jmrenouard** [major/MySQLTuner-perl#87]
Hello,

Is there anybody try to run this script from a windows OS ?

Is it compatible with Windows ?

Best regards.

**Comment by toshniba** [comment]
says `* Windows OS(Win7) is not supported.`

**Comment by jmrenouard** [comment]
Ok, Windows is no more blocked !
But I can't say what kind of result you can have using mysqltuner on it.

Best regards,

**Comment by toshniba** [comment]
there are lots of troubles on windows:

- backticks don't work as most/all commands do not exist on windows (eg `which`)
- script is unable to find mysql (or mysqladmin); even adding bin dir to `$PATH` did not work
- escape commands not supported (for colored output). maybe some module would fix this issue. (`[←[0;34m--←[0m]`)

**Comment by jmrenouard** [comment]
Thanks for your feedback

Do you try msys2, cygwin or other unix compatibility layer ?
It is maybe an alternative under Windows.

**Comment by 0xbsec** [comment]
@jmrenouard @toshniba I've test it using msys2 ( and added mysql bin path to `$PATH` ):
![windowsporterrors](https://cloud.githubusercontent.com/assets/8887221/13074956/8a79f3fa-d4b0-11e5-82a5-1a8680142a61.PNG)
the problem is that it isn't able to get `$physical_memory` & `$swap_memory`, it can be fixed by adding this exception in `os_setup` sub:

```
		elsif( $os =~ /windows/ ) {
            $physical_memory =
              `wmic ComputerSystem get TotalPhysicalMemory | perl -ne "chomp; print if /[0-9]+/;"`
              or memerror;
            $swap_memory     =
     		  `wmic OS get FreeVirtualMemory | perl -ne "chomp; print if /[0-9]+/;"`
              or memerror;
		}
```
After adding:
![windowsporterrorsafter](https://cloud.githubusercontent.com/assets/8887221/13075160/d6269276-d4b1-11e5-8ed1-b46e0b270f68.PNG)
I'm still testing.

**Comment by jmrenouard** [comment]
I closed this issue and if you get a specific problem open a new issue with a more specific details per error found.

Thanks for your help and your support :)
@0xbsec @toshniba
